import { Card, CardType, EffectTrigger, EffectAction } from "./index";

type RawCard = Omit<Card, "id"> & { id?: string };

const cardsRaw: RawCard[] = [
  // ─── BABY UNICORNS (×13, 1 each) ──────────────────────────
  { name: "Bebé Unicornio (Rojo)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-001-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Rosa)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-002-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Naranja)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-003-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Amarillo)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-004-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Verde)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-005-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Azul)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-006-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Púrpura)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-007-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Negro)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-008-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Blanco)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-009-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Marrón)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-010-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Arcoíris)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-011-SP.png", isBabyUnicorn: true },
  { name: "Bebé Unicornio (Muerte)", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-012-SP.png", isBabyUnicorn: true },
  { name: "Bebé Narval", type: CardType.BabyUnicorn, effect: "", image: "UU-Base-013-SP.png", isBabyUnicorn: true },

  // ─── BASIC UNICORNS (×22) ─────────────────────────────────
  { name: "Unicornio Básico (Rojo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-014-SP.png" },
  { name: "Unicornio Básico (Rojo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-014-SP.png" },
  { name: "Unicornio Básico (Rojo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-014-SP.png" },
  { name: "Unicornio Básico (Naranja)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-015-SP.png" },
  { name: "Unicornio Básico (Naranja)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-015-SP.png" },
  { name: "Unicornio Básico (Naranja)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-015-SP.png" },
  { name: "Unicornio Básico (Amarillo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-016-SP.png" },
  { name: "Unicornio Básico (Amarillo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-016-SP.png" },
  { name: "Unicornio Básico (Amarillo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-016-SP.png" },
  { name: "Unicornio Básico (Verde)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-017-SP.png" },
  { name: "Unicornio Básico (Verde)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-017-SP.png" },
  { name: "Unicornio Básico (Verde)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-017-SP.png" },
  { name: "Unicornio Básico (Azul)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-018-SP.png" },
  { name: "Unicornio Básico (Azul)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-018-SP.png" },
  { name: "Unicornio Básico (Azul)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-018-SP.png" },
  { name: "Unicornio Básico (Índigo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-019-SP.png" },
  { name: "Unicornio Básico (Índigo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-019-SP.png" },
  { name: "Unicornio Básico (Índigo)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-019-SP.png" },
  { name: "Unicornio Básico (Púrpura)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-020-SP.png" },
  { name: "Unicornio Básico (Púrpura)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-020-SP.png" },
  { name: "Unicornio Básico (Púrpura)", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-020-SP.png" },
  { name: "Narval", type: CardType.BasicUnicorn, effect: "", image: "UU-Base-021-SP.png" },

  // ─── MAGICAL UNICORNS (×30, 1 each) ───────────────────────
  {
    name: "Rinoceronte",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes HURTAR una carta de Ventaja.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Steal, target: { type: "any_upgrade" }, optional: true },
    image: "UU-Base-022-SP.png",
  },
  {
    name: "Gatórnico Mágico",
    type: CardType.MagicalUnicorn,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes ROBAR una carta.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Draw, target: { type: "none" }, optional: true },
    image: "UU-Base-023-SP.png",
  },
  {
    name: "Unicornio Puñal",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes DESTRUIR una carta de Unicornio.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Destroy, target: { type: "any_unicorn" }, optional: true },
    image: "UU-Base-024-SP.png",
  },
  {
    name: "Unicornio Arcoíris",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes robar un Bebé Unicornio de la Guardería.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.GainBaby, target: { type: "nursery" }, optional: true },
    image: "UU-Base-026-SP.png",
  },
  {
    name: "Unicornio Extremadamente Destructivo",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes DESTRUIR hasta 2 cartas de Unicornio.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Destroy, target: { type: "any_unicorn" }, optional: true, amount: 2 },
    image: "UU-Base-028-SP.png",
  },
  {
    name: "Unicornio Motosierra",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes SACRIFICAR una carta, luego DESTRUIR una carta.",
    effectData: {
      trigger: EffectTrigger.OnEnter, action: EffectAction.Sacrifice, target: { type: "self" }, optional: true,
      then: { trigger: EffectTrigger.OnEnter, action: EffectAction.Destroy, target: { type: "any_stable_card" }, optional: false },
    },
    image: "UU-Base-029-SP.png",
  },
  {
    name: "Llamicornio",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes buscar en el mazo una carta de Desventaja y añadirla a tu mano.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Draw, target: { type: "any_downgrade" }, optional: true },
    image: "UU-Base-030-SP.png",
  },
  {
    name: "Americornio",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes HURTAR una carta de Desventaja.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Steal, target: { type: "any_downgrade" }, optional: true },
    image: "UU-Base-031-SP.png",
  },
  {
    name: "Unicornio Gigantesco",
    type: CardType.MagicalUnicorn,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes SACRIFICAR una carta, luego DESTRUIR una carta.",
    effectData: {
      trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Sacrifice, target: { type: "self" }, optional: true,
      then: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Destroy, target: { type: "any_stable_card" }, optional: false },
    },
    image: "UU-Base-032-SP.png",
  },
  {
    name: "Unicornio Seductor",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes HURTAR una carta de Unicornio Básico.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Steal, target: { type: "any_unicorn" }, optional: true },
    image: "UU-Base-033-SP.png",
  },
  {
    name: "Unicornio Reina del Baile",
    type: CardType.MagicalUnicorn,
    effect: "Las cartas de Unicornio Básico no pueden entrar en el Establo de ningún otro jugador.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.PreventEntry, target: { type: "all_players" }, optional: false, cardTypeFilter: CardType.BasicUnicorn },
    image: "UU-Base-035-SP.png",
  },
  {
    name: "Unicornio Volador Codicioso",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, roba una carta.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Draw, target: { type: "none" }, optional: false },
    image: "UU-Base-036-SP.png",
  },
  {
    name: "Unicornio Volador Molesto",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes elegir cualquier jugador. Ese jugador DESCARTA una carta. Si esta carta fuera a ser sacrificada o destruida, devuélvela a tu mano en su lugar.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Discard, target: { type: "any_player" }, optional: true },
    image: "UU-Base-037-SP.png",
  },
  {
    name: "Unicornio Volador Mágico",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes buscar en el mazo una carta de Magia y añadirla a tu mano.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Draw, target: { type: "none" }, optional: true },
    image: "UU-Base-038-SP.png",
  },
  {
    name: "Unicornio Volador Veloz",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes realizar una acción adicional este turno.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.ExtraAction, target: { type: "none" }, optional: true },
    image: "UU-Base-039-SP.png",
  },
  {
    name: "Unicornio Volador Majestuoso",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes elegir cualquier jugador. Ese jugador DESCARTA 2 cartas.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Discard, target: { type: "any_player" }, optional: true, amount: 2 },
    image: "UU-Base-040-SP.png",
  },
  {
    name: "Fénix Unicornio",
    type: CardType.MagicalUnicorn,
    effect: "Si esta carta fuera a ser destruida, puedes SACRIFICAR otra carta en tu lugar.",
    image: "UU-Base-041-SP.png",
  },
  {
    name: "Unicornio Mazorca",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes HURTAR una carta de Ventaja.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Steal, target: { type: "any_upgrade" }, optional: true },
    image: "UU-Base-042-SP.png",
  },
  {
    name: "Unicornio Caballero Negro",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes DESTRUIR una carta de Ventaja.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Destroy, target: { type: "any_upgrade" }, optional: true },
    image: "UU-Base-043-SP.png",
  },
  {
    name: "Tiburón con Cuerno",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes DESTRUIR una carta de Unicornio Mágico.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Destroy, target: { type: "any_unicorn" }, optional: true },
    image: "UU-Base-044-SP.png",
  },
  {
    name: "Narval Andrajoso",
    type: CardType.MagicalUnicorn,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes ROBAR una carta.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Draw, target: { type: "none" }, optional: true },
    image: "UU-Base-045-SP.png",
  },
  {
    name: "Narval Torpedo",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes DESTRUIR una carta de Desventaja.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Destroy, target: { type: "any_downgrade" }, optional: true },
    image: "UU-Base-046-SP.png",
  },
  {
    name: "Narval Seductor",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes HURTAR una carta de Ventaja.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Steal, target: { type: "any_upgrade" }, optional: true },
    image: "UU-Base-047-SP.png",
  },
  {
    name: "Unicornio Sirena",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes HURTAR una carta de Unicornio Básico.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Steal, target: { type: "any_unicorn" }, optional: true },
    image: "UU-Base-048-SP.png",
  },
  {
    name: "Narval con Clase",
    type: CardType.MagicalUnicorn,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes ROBAR una carta, luego DESCARTAR una carta.",
    effectData: {
      trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Draw, target: { type: "none" }, optional: true,
      then: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Discard, target: { type: "self" }, optional: false },
    },
    image: "UU-Base-049-SP.png",
  },
  {
    name: "El Gran Narval",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes HURTAR una carta de Unicornio Mágico.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Steal, target: { type: "any_unicorn" }, optional: true },
    image: "UU-Base-050-SP.png",
  },
  {
    name: "Unicornio Ángel Oscuro",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes DESTRUIR una carta de Unicornio Mágico.",
    effectData: { trigger: EffectTrigger.OnEnter, action: EffectAction.Destroy, target: { type: "any_unicorn" }, optional: true },
    image: "UU-Base-088-SP.png",
  },
  {
    name: "Unicornio Mamá Ganso",
    type: CardType.MagicalUnicorn,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes robar un Bebé Unicornio de la Guardería.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.GainBaby, target: { type: "nursery" }, optional: true },
    image: "UU-Base-085-SP.png",
  },
  {
    name: "Unicornio Nigromante",
    type: CardType.MagicalUnicorn,
    effect: "Al inicio de tu turno, puedes robar una carta de Unicornio de la pila de descartes y ponerla en tu Establo.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Draw, target: { type: "none" }, optional: true },
    image: "UU-Base-087-SP.png",
  },
  {
    name: "Oráculo Unicornio",
    type: CardType.MagicalUnicorn,
    effect: "Cuando esta carta entra en tu Establo, puedes robar 3 cartas. Si lo haces, DESCARTA 2 cartas.",
    effectData: {
      trigger: EffectTrigger.OnEnter, action: EffectAction.Draw, target: { type: "none" }, optional: true, amount: 3,
      then: { trigger: EffectTrigger.OnEnter, action: EffectAction.Discard, target: { type: "self" }, optional: false, amount: 2 },
    },
    image: "UU-Base-086-SP.png",
  },

  // ─── MAGIC CARDS (×25) ────────────────────────────────────
  {
    name: "Veneno de Unicornio", type: CardType.Magic,
    effect: "DESTRUYE una carta de Unicornio.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Destroy, target: { type: "any_unicorn" }, optional: false },
    image: "UU-Base-051-SP.png",
  },
  { name: "Veneno de Unicornio", type: CardType.Magic, effect: "DESTRUYE una carta de Unicornio.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Destroy, target: { type: "any_unicorn" }, optional: false }, image: "UU-Base-051-SP.png" },
  { name: "Veneno de Unicornio", type: CardType.Magic, effect: "DESTRUYE una carta de Unicornio.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Destroy, target: { type: "any_unicorn" }, optional: false }, image: "UU-Base-051-SP.png" },
  {
    name: "Patada Trasera", type: CardType.Magic,
    effect: "Devuelve una carta de Unicornio a la mano de su dueño.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.ReturnToHand, target: { type: "any_unicorn" }, optional: false },
    image: "UU-Base-052-SP.png",
  },
  { name: "Patada Trasera", type: CardType.Magic, effect: "Devuelve una carta de Unicornio a la mano de su dueño.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.ReturnToHand, target: { type: "any_unicorn" }, optional: false }, image: "UU-Base-052-SP.png" },
  { name: "Patada Trasera", type: CardType.Magic, effect: "Devuelve una carta de Unicornio a la mano de su dueño.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.ReturnToHand, target: { type: "any_unicorn" }, optional: false }, image: "UU-Base-052-SP.png" },
  {
    name: "Cambio de Suerte", type: CardType.Magic,
    effect: "DESCARTA una carta, luego ROBA 2 cartas.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Discard, target: { type: "self" }, optional: false, then: { trigger: EffectTrigger.OnPlay, action: EffectAction.Draw, target: { type: "none" }, optional: false, amount: 2 } },
    image: "UU-Base-053-SP.png",
  },
  { name: "Cambio de Suerte", type: CardType.Magic, effect: "DESCARTA una carta, luego ROBA 2 cartas.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Discard, target: { type: "self" }, optional: false, then: { trigger: EffectTrigger.OnPlay, action: EffectAction.Draw, target: { type: "none" }, optional: false, amount: 2 } }, image: "UU-Base-053-SP.png" },
  {
    name: "Tornado de Purpurina", type: CardType.Magic,
    effect: "Devuelve todas las cartas de Ventaja y Desventaja a las manos de sus dueños.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.ReturnToHand, target: { type: "all_players" }, optional: false },
    image: "UU-Base-054-SP.png",
  },
  { name: "Tornado de Purpurina", type: CardType.Magic, effect: "Devuelve todas las cartas de Ventaja y Desventaja a las manos de sus dueños.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.ReturnToHand, target: { type: "all_players" }, optional: false }, image: "UU-Base-054-SP.png" },
  {
    name: "Intercambio de Unicornios", type: CardType.Magic,
    effect: "Intercambia un Unicornio de tu Establo por uno del Establo de otro jugador.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Steal, target: { type: "other_unicorn" }, optional: false },
    image: "UU-Base-055-SP.png",
  },
  { name: "Intercambio de Unicornios", type: CardType.Magic, effect: "Intercambia un Unicornio de tu Establo por uno del Establo de otro jugador.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Steal, target: { type: "other_unicorn" }, optional: false }, image: "UU-Base-055-SP.png" },
  {
    name: "Redireccionar", type: CardType.Magic,
    effect: "Cambia el objetivo de una carta de Magia a otro objetivo válido.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.None, target: { type: "none" }, optional: false },
    image: "UU-Base-056-SP.png",
  },
  { name: "Redireccionar", type: CardType.Magic, effect: "Cambia el objetivo de una carta de Magia a otro objetivo válido.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-056-SP.png" },
  {
    name: "Trato Injusto", type: CardType.Magic,
    effect: "ROBA 2 cartas. Todos los demás jugadores ROBAN una carta.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Draw, target: { type: "self" }, optional: false, amount: 2 },
    image: "UU-Base-057-SP.png",
  },
  { name: "Trato Injusto", type: CardType.Magic, effect: "ROBA 2 cartas. Todos los demás jugadores ROBAN una carta.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Draw, target: { type: "self" }, optional: false, amount: 2 }, image: "UU-Base-057-SP.png" },
  {
    name: "Dos por Uno", type: CardType.Magic,
    effect: "SACRIFICA una carta de Unicornio, luego DESTRUYE una carta.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Sacrifice, target: { type: "self" }, optional: false, cardTypeFilter: CardType.BabyUnicorn, then: { trigger: EffectTrigger.OnPlay, action: EffectAction.Destroy, target: { type: "any_stable_card" }, optional: false } },
    image: "UU-Base-058-SP.png",
  },
  { name: "Dos por Uno", type: CardType.Magic, effect: "SACRIFICA una carta de Unicornio, luego DESTRUYE una carta.", effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Sacrifice, target: { type: "self" }, optional: false, cardTypeFilter: CardType.BabyUnicorn, then: { trigger: EffectTrigger.OnPlay, action: EffectAction.Destroy, target: { type: "any_stable_card" }, optional: false } }, image: "UU-Base-058-SP.png" },
  {
    name: "Destrucción Selectiva", type: CardType.Magic,
    effect: "DESTRUYE una carta de Ventaja o Desventaja.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Destroy, target: { type: "any_upgrade" }, optional: false },
    image: "UU-Base-060-SP.png",
  },
  {
    name: "Vórtice Místico", type: CardType.Magic,
    effect: "Cada jugador SACRIFICA un Unicornio.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Sacrifice, target: { type: "all_players" }, optional: false, cardTypeFilter: CardType.BabyUnicorn },
    image: "UU-Base-061-SP.png",
  },
  {
    name: "Buen Negocio", type: CardType.Magic,
    effect: "HURTA una carta de Unicornio.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Steal, target: { type: "any_unicorn" }, optional: false },
    image: "UU-Base-062-SP.png",
  },
  {
    name: "Sacudida", type: CardType.Magic,
    effect: "Baraja todas las cartas de Unicornio de todos los Establos en el mazo y repártelas de nuevo.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.ShuffleIntoDeck, target: { type: "all_players" }, optional: false },
    image: "UU-Base-063-SP.png",
  },
  {
    name: "Robo Descarado", type: CardType.Magic,
    effect: "HURTA una carta de Unicornio. Los Bebés Unicornio robados vuelven a la Guardería.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Steal, target: { type: "any_unicorn" }, optional: false },
    image: "UU-Base-064-SP.png",
  },
  {
    name: "Botón de Reinicio", type: CardType.Magic,
    effect: "Cada jugador SACRIFICA todas las cartas de Ventaja y Desventaja. Baraja la pila de descartes en el mazo.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Sacrifice, target: { type: "all_players" }, optional: false },
    image: "UU-Base-065-SP.png",
  },
  {
    name: "Beso de Vida", type: CardType.Magic,
    effect: "Coge una carta de Unicornio de la pila de descartes y ponla en tu Establo.",
    effectData: { trigger: EffectTrigger.OnPlay, action: EffectAction.Draw, target: { type: "none" }, optional: false },
    image: "UU-Base-089-SP.png",
  },

  // ─── UPGRADE CARDS (×14) ──────────────────────────────────
  {
    name: "Sobrecarga de Cafeína", type: CardType.Upgrade,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes realizar una acción adicional.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.ExtraAction, target: { type: "none" }, optional: true },
    image: "UU-Base-093-SP.png",
  },
  {
    name: "Máquina de Garra", type: CardType.Upgrade,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes robar un Bebé Unicornio de la Guardería.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.GainBaby, target: { type: "nursery" }, optional: true },
    image: "UU-Base-090-SP.png",
  },
  { name: "Máquina de Garra", type: CardType.Upgrade, effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes robar un Bebé Unicornio de la Guardería.", effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.GainBaby, target: { type: "nursery" }, optional: true }, image: "UU-Base-090-SP.png" },
  { name: "Máquina de Garra", type: CardType.Upgrade, effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes robar un Bebé Unicornio de la Guardería.", effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.GainBaby, target: { type: "nursery" }, optional: true }, image: "UU-Base-090-SP.png" },
  {
    name: "Doble Salto", type: CardType.Upgrade,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes ROBAR una carta adicional.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Draw, target: { type: "none" }, optional: true },
    image: "UU-Base-072-SP.png",
  },
  {
    name: "Bomba de Purpurina", type: CardType.Upgrade,
    effect: "Las cartas que juegues no pueden ser Relincheadas.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.PreventNeigh, target: { type: "self" }, optional: false },
    image: "UU-Base-068-SP.png",
  },
  { name: "Bomba de Purpurina", type: CardType.Upgrade, effect: "Las cartas que juegues no pueden ser Relincheadas.", effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.PreventNeigh, target: { type: "self" }, optional: false }, image: "UU-Base-068-SP.png" },
  {
    name: "Aura Arcoíris", type: CardType.Upgrade,
    effect: "Los Unicornios que entren en tu Establo no pueden ser Relincheados.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.PreventNeigh, target: { type: "self" }, optional: false },
    image: "UU-Base-071-SP.png",
  },
  {
    name: "Lazo Arcoíris", type: CardType.Upgrade,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes HURTAR una carta de Ventaja.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Steal, target: { type: "any_upgrade" }, optional: true },
    image: "UU-Base-092-SP.png",
  },
  {
    name: "Artillería de Establo", type: CardType.Upgrade,
    effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes DESTRUIR una carta de Desventaja.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Destroy, target: { type: "any_downgrade" }, optional: true },
    image: "UU-Base-091-SP.png",
  },
  { name: "Artillería de Establo", type: CardType.Upgrade, effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes DESTRUIR una carta de Desventaja.", effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Destroy, target: { type: "any_downgrade" }, optional: true }, image: "UU-Base-091-SP.png" },
  { name: "Artillería de Establo", type: CardType.Upgrade, effect: "Si esta carta está en tu Establo al inicio de tu turno, puedes DESTRUIR una carta de Desventaja.", effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Destroy, target: { type: "any_downgrade" }, optional: true }, image: "UU-Base-091-SP.png" },
  {
    name: "¡Hurra!", type: CardType.Upgrade,
    effect: "Las cartas que juegues no pueden ser Relincheadas.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.PreventNeigh, target: { type: "self" }, optional: false },
    image: "UU-Base-069-SP.png",
  },
  { name: "¡Hurra!", type: CardType.Upgrade, effect: "Las cartas que juegues no pueden ser Relincheadas.", effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.PreventNeigh, target: { type: "self" }, optional: false }, image: "UU-Base-069-SP.png" },

  // ─── DOWNGRADE CARDS (×8, 1 each) ─────────────────────────
  {
    name: "Alambre de Espino", type: CardType.Downgrade,
    effect: "Si esta carta está en el Establo de un jugador al inicio de su turno, ese jugador SACRIFICA una carta de Unicornio.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Sacrifice, target: { type: "self" }, optional: false, cardTypeFilter: CardType.BabyUnicorn },
    image: "UU-Base-074-SP.png",
  },
  {
    name: "Pandamonio", type: CardType.Downgrade,
    effect: "Si esta carta está en el Establo de un jugador al inicio de su turno, ese jugador DESCARTA una carta al azar.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Discard, target: { type: "self" }, optional: false },
    image: "UU-Base-075-SP.png",
  },
  {
    name: "Ritual Sádico", type: CardType.Downgrade,
    effect: "Si esta carta está en el Establo de un jugador al inicio de su turno, ese jugador SACRIFICA un Unicornio.",
    effectData: { trigger: EffectTrigger.BeginningOfTurn, action: EffectAction.Sacrifice, target: { type: "self" }, optional: false, cardTypeFilter: CardType.BabyUnicorn },
    image: "UU-Base-076-SP.png",
  },
  {
    name: "Ralentización", type: CardType.Downgrade,
    effect: "Si esta carta está en el Establo de un jugador, ese jugador solo puede jugar una carta por turno.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.None, target: { type: "self" }, optional: false },
    image: "UU-Base-077-SP.png",
  },
  {
    name: "Cámara para la Niñera", type: CardType.Downgrade,
    effect: "Si esta carta está en el Establo de un jugador, ese jugador debe mostrar su mano al final de su turno.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.None, target: { type: "self" }, optional: false },
    image: "UU-Base-078-SP.png",
  },
  {
    name: "Establo Roto", type: CardType.Downgrade,
    effect: "Los Bebés Unicornio no cuentan para la victoria.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.None, target: { type: "all_players" }, optional: false },
    image: "UU-Base-079-SP.png",
  },
  {
    name: "Luz Cegadora", type: CardType.Downgrade,
    effect: "Si esta carta está en el Establo de un jugador, ese jugador no puede jugar cartas Instantáneas.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.None, target: { type: "self" }, optional: false },
    image: "UU-Base-080-SP.png",
  },
  {
    name: "Establo Diminuto", type: CardType.Downgrade,
    effect: "El límite de cartas en el Establo de este jugador es 5.",
    effectData: { trigger: EffectTrigger.Continuous, action: EffectAction.None, target: { type: "self" }, optional: false },
    image: "UU-Base-081-SP.png",
  },

  // ─── INSTANT CARDS (×15) ──────────────────────────────────
  {
    name: "Relincho", type: CardType.Instant,
    effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.",
    effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false },
    image: "UU-Base-082-SP.png",
  },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  { name: "Relincho", type: CardType.Instant, effect: "Juega esta carta cuando cualquier otro jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes.", effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false }, image: "UU-Base-082-SP.png" },
  {
    name: "Super Relincho", type: CardType.Instant,
    effect: "Juega esta carta cuando cualquier jugador intente jugar una carta. Detén esa carta y envíala a la pila de descartes. No puede ser Relincheada.",
    effectData: { trigger: EffectTrigger.Instant, action: EffectAction.None, target: { type: "none" }, optional: false },
    image: "UU-Base-083-SP.png",
  },
];

// Assign IDs and build the final array
let idCounter = 0;
export const ALL_CARDS: Card[] = cardsRaw.map((c) => ({
  ...c,
  id: c.id ?? `card_${String(++idCounter).padStart(3, "0")}`,
}));

// Get card by ID
export function getCardById(id: string): Card | undefined {
  return ALL_CARDS.find((c) => c.id === id);
}

// Get all baby unicorn cards (for initial selection)
export const BABY_UNICORNS: Card[] = ALL_CARDS.filter((c) => c.isBabyUnicorn);
